name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images (compose)
        run: docker compose build

      - name: Tag & push gateway-service
        run: |
          docker tag msnappmicro-gateway-service ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-gateway:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-gateway:latest

      - name: Tag & push user-service
        run: |
          docker tag msnappmicro-user-service ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-user:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-user:latest

      - name: Tag & push message-service
        run: |
          docker tag msnappmicro-message-service ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-message:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-message:latest

      - name: Tag & push notification-service
        run: |
          docker tag msnappmicro-notification-service ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-notification:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msnappmicro-notification:latest